version: '3'
services:
  home-page:
    image: nginx:alpine
    container_name: home-page
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./icons:/usr/share/nginx/html/icons:ro
      - ./images:/usr/share/nginx/html/images:ro
    restart: always
